import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

import Footer from "@/components/landing/Footer";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Baroda Residency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="fixed w-full z-50 bg-black/20 backdrop-blur-sm">
          <div className="container mx-auto px-4 py-4">
            <nav className="flex items-center justify-between">
              <Link href="/">
                <Image src="/logo.png" alt="StayLuxury Logo" width={150} height={50} />
              </Link>
              <div className="hidden md:flex items-center space-x-8">
                <Link href="/" className="text-white hover:text-yellow-400">Home</Link>
                <Link href="/banquets" className="text-white hover:text-yellow-400">Banquets</Link>
                <Link href="/dining" className="text-white hover:text-yellow-400">Dining</Link>
                <Link href="/rooms" className="text-white hover:text-yellow-400">Rooms</Link>
              </div>
              <Button className="bg-baryellow hover:bg-yellow-600 text-black">
                Enquire Now
              </Button>
            </nav>
          </div>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
